name: Build Dev Version Extension

on: [pull_request, push]

jobs:

  build-dev-extension:
    runs-on: ubuntu-latest 
    # Customise for extension
    env:
      EXT_NAME: codehighlighter2-Dev
      EXT_DIR: codehighlighter/
    
    steps:

      - name: Step 1 - Get repo
        uses: actions/checkout@v2

      - name: Step 2 - Enable development framework scripts
        run: |
          sed -i "s/<!-- //" ${{env.EXT_DIR}}META-INF/manifest.xml
          # cat ${{env.EXT_DIR}}META-INF/manifest.xml
          # echo
 
      - name: Step 3 - Update to dev version
        run: |
          sed -i '/<version value/ s/"\/>/-Dev"\/>/' ${{env.EXT_DIR}}description.xml
          # cat ${{env.EXT_DIR}}description.xml
          # echo
          
      - name: Step 4 - Build repo
        uses: vimtor/action-zip@v1
        with:
          files: ${{env.EXT_DIR}}
          dest: ${{env.EXT_NAME}}.oxt
          
      - name: Step 5 - Upload dev version
        uses: actions/upload-artifact@v2
        with: 
          name: ${{env.EXT_NAME}} - Extension in Zip file
          path: ${{env.EXT_NAME}}.oxt
